export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"

export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"


export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"

export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"


export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"

export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"

export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE"

export const SERVICES_REQUEST = "SERVICES_REQUEST"

export const SERVICES_SUCCESS = "SERVICES_SUCCESS"

export const SERVICES_FAILURE = "SERVICES_FAILURE"